### ISSUE TITLE
Plotly backend width and height

### ISSUE THREAD

**Issue by GitHunter0** [Davide-sd/sympy-plot-backends#15]
Congratulations for this amazing module.
I could not find a way to control the width an height of the plotly plot, is there an option to do that?
Thank you

**Comment by Davide-sd** [comment]
Hello @GitHunter0 , thanks for the kind words.

You can use the `size` keyword argument, for example:

```
plot(cos(x), backend=PB, size=(400, 200))
```

the first number is the width, the second is the height. For Plotly, both numbers represent pixels.

**Comment by GitHunter0** [comment]
Excellent, thank you @Davide-sd
