### ISSUE TITLE
Incompatibilities with Spyder 5.3.3 and Qt 5.15.2

### ISSUE THREAD

**Issue by BikePack** [Davide-sd/sympy-plot-backends#21]
I'm using Anaconda base packages from the Windows installation distro all updated with "conda update conda" after which the sequence of backend installations are executed per the instructions herein.  During the installations,  Spyder is updated from 5.1.5 to 5.3.3, for which Spyder 5.33 uses Qt 5.15.2.  Using the first plot_geometry example in the tutorial and then trying to customize the figure, the plot freezes the console making the console unusable unless the kernal is restarted.

I rolled backed to Syder 5.1.5 that uses Qt 5.9.7 and the first tutorial example is manipulated without any problem.

**Comment by Davide-sd** [comment]
Which python version are you using?

**Comment by BikePack** [comment]
Spyder says python 3.9.16.

**Comment by Davide-sd** [comment]
I created a [new installation recipe for conda](https://github.com/conda-forge/sympy_plot_backends-feedstock). Give it a try and let me know.

**Comment by BikePack** [comment]
With the following installed in the base environment with python 3.9.16:
conda install -c anaconda scipy notebook colorcet
conda install -c conda-forge adaptive
conda install -c conda-forge panel
conda install -c anaconda ipywidgets
conda install -c conda-forge ipympl
conda install -c bokeh ipywidgets_bokeh
conda install -c conda-forge k3d msgpack-python
conda install -c plotly plotly
conda install -c conda-forge vtk

And after executing the 3 conda commands
conda config --add channels conda-forge
conda config --set channel_priority strict
conda install sympy_plot_backends

conda is taking hours trying look for incompatible packages and has gotten this far:

Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: -
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
Examining conflict for transformers smart_open anaconda _anaconda_depends distributed:
Examining conflict for transformers jellyfish incremental python-dateutil pywavelets sympy ipython_genutils pyhamcrest twisted pycparser lxml ipympl lz4 regex websocket-client zipp k3d json5 urllib3 sympy_plo|

**Comment by Davide-sd** [comment]
Create a new environment. First install this:

```
conda config --add channels conda-forge
conda config --set channel_priority strict
conda install sympy_plot_backends
```

then install the rest. Give it a try.

**Comment by Davide-sd** [comment]
Closing this issue as I haven't heard anything back.
