### ISSUE TITLE
Installation failure on Linux Mint 21.1 -- glibc incompatibility

### ISSUE THREAD

**Issue by BikePack** [Davide-sd/sympy-plot-backends#23]
Using the latest Linux Anaconda distro updated with conda update conda, all of the backend packages install successfully except for sympy-plot-backends.

The Anaconda package manager says the sympy-plot-backends is incompatible with the operating system linux-64 glibc==2.35=0.

Anaconda result:

![image](https://user-images.githubusercontent.com/96804314/223912177-73839b11-7e23-4452-85f5-cc439ef0a16e.png)

My Mint 21.1 installation:

![image](https://user-images.githubusercontent.com/96804314/223912378-1973aeac-8bc4-4c4b-bb1f-a6eb7b33c957.png)

**Comment by BikePack** [comment]
Update:  On fresh install of the latest Anaconda Linux distro [Anaconda3-2023.03-Linux-x86_64.sh](https://repo.anaconda.com/archive/Anaconda3-2023.03-Linux-x86_64.sh) on Mint 21.1, the package manager fails to install sympy-plot-backends due to the same incompatibility identified above (glibc 2.35).

**Comment by Davide-sd** [comment]
Closing this issue as I haven't heard anything back.
