### ISSUE TITLE
Order axis by the order of values in the range parameter

### ISSUE THREAD

**Issue by James-G-Hill** [Davide-sd/sympy-plot-backends#26]
Would it be possible to allow ordering of the x axis by changing the order of values in a range?
There's an article on how it may be done in matplotlib here:

https://matplotlib.org/stable/gallery/subplots_axes_and_figures/invert_axes.html

However, changing:

```
(h, 0, 1)
```

to

```
(h, 1, 0)
```

has no effect.

**Comment by Davide-sd** [comment]
Hello James, I think it can be done. Expect a new release by the end of next week. In the meantime, you can achieve the same result by specifying `xlim=(1, 0)`.

**Comment by James-G-Hill** [comment]
Thanks for the tip

**Comment by Davide-sd** [comment]
I just released a new version which implements the requested behavior. It's already available on PyPi and should become available on Conda in a couple of days.

Thanks James for the suggestion. I'm closing this issue.
