### ISSUE TITLE
Document how to set colors in `plot_geometry`

### ISSUE THREAD

**Issue by James-G-Hill** [Davide-sd/sympy-plot-backends#27]
I cannot figure out how to set the color of an object when using `plot_geometry` such as here:
```
plot_geometry(
    (Segment((0, 0), (1, 0)), 'r')
)
```
I've tried adding variations on the following with different key names in the dictionary but nothing works for me:
```
plot_geometry(
    (Segment((0, 0), (1, 0)), 'r', {'color': 'red'})
)
```
Searching through the matplotlib backend links didn't reveal the magic keyword I need to be using. Maybe it would be good to demonstrate how to do this in one of the documented examples for `plot_geometry`?

**Comment by Davide-sd** [comment]
Hello James, that's a bug...

For the moment you can use the `rendering_kw` keyword argument:

```py
plot_geometry(
    Segment((0, 0), (1, 0)), 'r', rendering_kw={"color": "g"}
)
```

**Comment by Davide-sd** [comment]
I just released a new version which fixes this bug. It's already available on PyPi and should become available on Conda in a couple of days.

Thanks James for opening this issue. I'm closing it now.
