### ISSUE TITLE
why the figure-size gets smaller after setting "ax"

### ISSUE THREAD

**Issue by imakn634** [Davide-sd/sympy-plot-backends#37]
I would like to know why the figure-size gets smaller after setting "ax". 
Is is possible for the size to remain unchanged? 

```python
from sympy.abc import *
from sympy import *
from spb import *

plot(-x**2, (x, -1, 1))
```
![fig1](https://github.com/Davide-sd/sympy-plot-backends/assets/85376738/db00fe46-89ee-4f87-a758-67cf522b5df6)

```python
p=plot(-x**2, (x, -1, 1), show=False)
ax=p.ax
ax.grid(linestyle = 'dotted')
```
![fig2](https://github.com/Davide-sd/sympy-plot-backends/assets/85376738/864c16c3-363a-4f9a-bef9-e0dfda2c8640)

After setting "ax=p.ax", the figure-size gets slightly smaller.  

If possible, I would like to know how to set the size unchanged.

**Comment by Davide-sd** [comment]
Because the `p.show` method applies [`tigh_layout()`](https://matplotlib.org/stable/api/_as_gen/matplotlib.pyplot.tight_layout.html) to the figure:

```py
p = plot(-t**2, (t, -1, 1), show=False)
fig = p.fig
ax = p.ax
fig.tight_layout()
ax.grid(linestyle = 'dotted')
```

**Comment by imakn634** [comment]
Thank you! `fig.tight_layout()` woks!

**Comment by Davide-sd** [comment]
I'm closing the issue :)
