### ISSUE TITLE
Welcome to the awesome-list for Panel

### ISSUE THREAD

**Issue by MarcSkovMadsen** [Davide-sd/sympy-plot-backends#4]
Hi Davide

I checked out the repository and added it to the awesome-list for Panel.

https://awesome-panel.org/awesome-list?search=sympy

![image](https://user-images.githubusercontent.com/42288570/147400585-247b6197-43a5-4541-919b-7ccfebd5117d.png)

I'm a contributor to Panel. Maintain https://awesome-panel.org/ and post about Panel at https://www.linkedin.com/in/marcskovmadsen/ and https://twitter.com/MarcSkovMadsen.

**Comment by Davide-sd** [comment]
Hello @MarcSkovMadsen , thank you.

What a wonderful list of panel applications!!! :)
