### ISSUE TITLE
Small typos in installation documentation

### ISSUE THREAD

**Issue by gutow** [Davide-sd/sympy-plot-backends#5]
I believe following two lines in the installation documentation need double hyphens rather than single.
```
 jupyter nbextension install –user –py k3d
 jupyter nbextension enable –user –py k3d
```
They should read:
```
 jupyter nbextension install --user --py k3d
 jupyter nbextension enable --user --py k3d
```
Just started testing package. It looks really good. Thank you!

**Comment by Davide-sd** [comment]
Thank you very much! :) Fixed it.
