### ISSUE TITLE
update conda package to 3.10

### ISSUE THREAD

**Issue by sadguitarius** [Davide-sd/sympy-plot-backends#7]
Hi @Davide-sd, would it be possible for you to add Python 3.10 to the allowed versions in the conda package, or is something not working with 3.10?

Thanks!

**Comment by Davide-sd** [comment]
Hello @sadguitarius . I tried to add it a few months back but the build failed, so I removed it. I'll look into it again soon (I should have a new minor version coming up by the end of the week)!

**Comment by sadguitarius** [comment]
Ah great, thank you!

**Comment by Davide-sd** [comment]
I tried again with no luck. Looking for the error message, it appears that other packages are experiencing the same problem that I'm encountering on my conda build.

Note that I can't build on Pypi with Python 3.10 either, as `vtk` still hasn't been released for this version.

I'll keep you posted.

**Comment by sadguitarius** [comment]
Thanks for letting me know. I had thought it was more urgent to upgrade because of some recent bugs in Jupyterlab, but it turns out that the issues remain on 3.10, so I'll stick with 3.9 for now.

**Comment by Davide-sd** [comment]
Finally I have been able to build the conda package for Python 3.10. I'm closing this issue.
